/* Ingenieurswerkboek: verwante voorbeelde bly onder hul betrokke leersubonderwerp. */
import { Play } from "lucide-react";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import "./example-expansions.css";
import "./adder-example-tables.css";
import "./two-complement-reminder.css";

type Example = { title: string; rows: string[] };
const le2: Array<{ title: string; examples: Example[] }> = [
  { title: "1. Teken en omvang", examples: [{ title: "Voorbeeld A: +5", rows: ["0 | 101", "0 wys positief; 101₂ = 5.", "Dus: +5."] }, { title: "Voorbeeld B: −5", rows: ["1 | 101", "1 wys negatief; omvang bly 101₂ = 5.", "Dus: −5."] }] },
  { title: "2. Twee-komplement voorstelling", examples: [{ title: "Voorbeeld A: −3", rows: ["+3 = 0011", "Inverseer: 1100", "Tel 1 by: 1101 = −3."] }, { title: "Voorbeeld B: −6", rows: ["+6 = 0110", "Inverseer: 1001", "Tel 1 by: 1010 = −6."] }] },
  { title: "Uitbreiding van buslengte", examples: [{ title: "Voorbeeld A: unsigned", rows: ["1011₂ na 8 bis", "Voeg nulle links by.", "0000 1011₂."] }, { title: "Voorbeeld B: getekend", rows: ["1011₂ na 8 bis", "Tekenbis is 1; herhaal dit links.", "1111 1011₂."] }] },
  { title: "Oorloopreël", examples: [{ title: "Voorbeeld A: positiewe oorloop", rows: ["0111 (+7) + 0001 (+1)", "= 1000 (negatiewe tekenpatroon)", "Twee + insette, − resultaat: oorloop."] }, { title: "Voorbeeld B: negatiewe oorloop", rows: ["1000 (−8) + 1111 (−1)", "= 0111 (positiewe tekenpatroon)", "Twee − insette, + resultaat: oorloop."] }] },
  { title: "Maal v. positiewe getalle", examples: [{ title: "Voorbeeld A: 5 × 3", rows: ["C=0, A=0000, Q=0011, M=0101.", "Toets Q₀; tel M by A indien Q₀=1; skuif C-A-Q.", "Finale A|Q = 0000 1111 = 15."] }, { title: "Voorbeeld B: 4 × 6", rows: ["C=0, A=0000, Q=0110, M=0100.", "Werk vier toets/tel/skuif-rye.", "Finale A|Q = 0001 1000 = 24."] }] },
];

const multiplicationExampleTables = [
  { title: "Voorbeeld A · 5 × 3", headers: ["Stap", "C", "A", "Q", "M", "Nota / aksie"], rows: [["Begin", "0", "0000", "0011", "0101", "Q₀=1; begin"], ["Siklus 1", "0", "0010", "1001", "0101", "A←A+M; skuif"], ["Siklus 2", "0", "0011", "1100", "0101", "A←A+M; skuif"], ["Siklus 3", "0", "0001", "1110", "0101", "Q₀=0; slegs skuif"], ["Siklus 4", "0", "0000", "1111", "0101", "Q₀=0; slegs skuif"]], result: "A|Q = 0000 1111 = 15" },
  { title: "Voorbeeld B · 4 × 6", headers: ["Stap", "C", "A", "Q", "M", "Nota / aksie"], rows: [["Begin", "0", "0000", "0110", "0100", "Q₀=0; begin"], ["Siklus 1", "0", "0000", "0011", "0100", "Q₀=0; slegs skuif"], ["Siklus 2", "0", "0010", "0001", "0100", "A←A+M; skuif"], ["Siklus 3", "0", "0011", "0000", "0100", "A←A+M; skuif"], ["Siklus 4", "0", "0001", "1000", "0100", "Q₀=0; slegs skuif"]], result: "A|Q = 0001 1000 = 24" },
] as const;

const divisionExampleTables = [
  { title: "Voorbeeld A · 147 ÷ 11", quotient: "00001101", divisor: "1011", dividend: "10010011", remainder: "0100", rows: [["−", "1 < 1011; skryf 0"], ["+", "10 < 1011; skryf 0"], ["−", "100 < 1011; skryf 0"], ["+", "1001 < 1011; skryf 0"], ["−", "10010 − 01011 = 00111; skryf 1"], ["+", "1110 − 1011 = 0011; skryf 1"], ["−", "111 < 1011; skryf 0"], ["+", "1111 − 1011 = 0100; skryf 1"]], result: "13 res 4 · 00001101₂, res 0100₂" },
  { title: "Voorbeeld B · 84 ÷ 7", quotient: "00001100", divisor: "0111", dividend: "01010100", remainder: "0000", rows: [["−", "0 < 0111; skryf 0"], ["+", "01 < 0111; skryf 0"], ["−", "010 < 0111; skryf 0"], ["+", "0101 < 0111; skryf 0"], ["−", "1010 − 0111 = 0011; skryf 1"], ["+", "0111 − 0111 = 0000; skryf 1"], ["−", "0 < 0111; skryf 0"], ["+", "00 < 0111; skryf 0"]], result: "12 res 0 · 00001100₂, res 0000₂" },
] as const;
function MultiplicationExampleTables() { return <div className="example-table-grid">{multiplicationExampleTables.map((item) => <section className="example-table-card" key={item.title}><header><b>{item.title}</b><span>{item.result}</span></header><div className="example-table-scroll"><table><thead><tr>{item.headers.map((head) => <th key={head}>{head}</th>)}</tr></thead><tbody>{item.rows.map((row, index) => <tr key={`${item.title}-${index}`}>{row.map((cell, cellIndex) => <td key={`${item.title}-${index}-${cellIndex}`}>{cell}</td>)}</tr>)}</tbody></table></div></section>)}</div>; }

function DivisionExampleBlock() { const [open, setOpen] = useState(false); return <article className="expansion expansion--division"><header><span>DELING</span><button type="button" onClick={() => setOpen(!open)}><Play className="size-3.5" />{open ? "Versteek 2 voorbeelde" : "Wys 2 voorbeelde"}</button></header>{open ? <div className="division-example-grid">{divisionExampleTables.map((item) => <section className="division-example-card" key={item.title}><header><b>{item.title}</b><span>Binêre langdeling</span></header><div className="division-example__sheet"><div className="division-example__top"><div className="division-example__divisor"><em>Deler</em><code>{item.divisor}</code></div><div className="division-example__values"><div><em>Heelgetal antw deel in biner</em><code>{item.quotient}</code></div><div><em>Getal wat mee gedeel word</em><code>{item.dividend}</code></div></div></div><div className="division-example__work">{item.rows.map(([sign, operation], index) => <div className="division-example__line" key={`${item.title}-${index}`}><b>{sign}</b><code>{operation}</code></div>)}</div><div className="division-example__result"><em>Res deel v. antw in biner</em><code>{item.remainder}</code></div></div><p className="division-example-card__answer"><b>Antwoord:</b> {item.result}</p></section>)}</div> : null}</article>; }

const le3: Array<{ title: string; examples: Example[] }> = [
  { title: "HALWE OPTELLER", examples: [{ title: "Voorbeeld A: 1 + 1", rows: ["A=1, B=1", "S = A XOR B = 0", "C = A AND B = 1 → 10₂."] }, { title: "Voorbeeld B: 1 + 0", rows: ["A=1, B=0", "S = 1 XOR 0 = 1", "C = 1 AND 0 = 0 → 01₂."] }] },
  { title: "VOLOPTELLER", examples: [{ title: "Voorbeeld A: 1 + 1 + Cin 1", rows: ["A=1, B=1, Cin=1", "Som = 1; Cout = 1.", "Dus 1+1+1 = 11₂."] }, { title: "Voorbeeld B: 1 + 0 + Cin 1", rows: ["A=1, B=0, Cin=1", "Som = 0; Cout = 1.", "Dus 1+0+1 = 10₂."] }] },
];
function ExampleBlock({ item }: { item: { title: string; examples: Example[] } }) { const [open, setOpen] = useState(false); const isMultiplication = item.title === "Maal v. positiewe getalle"; return <article className={`expansion ${isMultiplication ? "expansion--multiplication" : ""}`}><header><span>{item.title}</span><button type="button" onClick={() => setOpen(!open)}><Play className="size-3.5" />{open ? "Versteek voorbeelde" : "Wys 2 voorbeelde"}</button></header>{open ? isMultiplication ? <MultiplicationExampleTables /> : <div>{item.examples.map(example => <section key={example.title}><b>{example.title}</b><ol>{example.rows.map(row => <li key={row}>{row}</li>)}</ol></section>)}</div> : null}</article>; }
function TwoComplementPlusOneReminder(){const [target,setTarget]=useState<HTMLElement|null>(null);useEffect(()=>{const article=Array.from(document.querySelectorAll<HTMLElement>(".negative-numbers__methods article")).find((item)=>item.querySelector("h4")?.textContent?.includes("Twee-komplement"));setTarget(article??null)},[]);if(!target)return null;return createPortal(<aside className="two-complement-reminder" aria-label="Twee-komplement plus een herinnering"><span>MOENIE DIE +1 VERGEET NIE</span><strong>2-KOMPLEMENT = KOMPLEMENT + 1</strong><div className="two-complement-reminder__steps"><div><b>STAP 1 · KOMPLEMENT</b><code>+3: 0011 → 1100</code><small>Inverseer elke bis: 0 word 1; 1 word 0.</small></div><i>+</i><div><b>STAP 2 · TEL ALTYD 1 BY</b><code>1100 + 0001 = 1101</code><small><b>1101</b> is die twee-komplement vir −3.</small></div></div><p><b>Onthou:</b> sonder die <b>+1</b> het jy slegs die een-komplement, nie die twee-komplement nie.</p></aside>,target)}
export function Le2ExampleExpansions() { return <><TwoComplementPlusOneReminder/><section className="example-expansions"><header><span>LE2 / VOORBEELDE PER SUBOPSKRIF</span><h4>Open net die metode wat jy nou hersien.</h4></header>{le2.map(item => <ExampleBlock item={item} key={item.title} />)}<DivisionExampleBlock /></section></>; }
export function Le3ExampleExpansions() { const [open,setOpen]=useState(""); const table=(id:string,title:string,heads:string[],rows:string[][])=><article className="expansion expansion--adder"><header><span>{title}</span><button type="button" onClick={()=>setOpen(open===id?"":id)}><Play className="size-3.5"/>{open===id?"Versteek voorbeelde":"Wys 2 voorbeelde"}</button></header>{open?<div className="adder-examples"><table><thead><tr>{heads.map(head=><th key={head}>{head}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table><p><b>Lees die gemerkte rye:</b> elke ry toon een volledige voorbeeld met insette, Som en oordrag.</p></div>:null}</article>; return <section className="example-expansions example-expansions--logic"><header><span>LE3 / OPTELLERVOORBEELDE</span><h4>Vergelyk die insette, Som en oordrag in waarheidstabelvorm.</h4></header>{table("half","HALWE OPTELLER",["Voorbeeld","A","B","S","C"],[["A","1","1","0","1"],["B","1","0","1","0"]])}{table("full","VOLOPTELLER",["Voorbeeld","A","B","Cin","Som","Cout"],[["A","1","1","1","1","1"],["B","1","0","1","0","1"]])}</section>; }
