/* Ingenieurswerkboek: verwante voorbeelde bly onder hul betrokke leersubonderwerp. */
import { Play } from "lucide-react";
import { useState } from "react";
import "./example-expansions.css";
import "./adder-example-tables.css";

type Example = { title: string; rows: string[] };
const le2: Array<{ title: string; examples: Example[] }> = [
  { title: "1. Teken en omvang", examples: [{ title: "Voorbeeld A: +5", rows: ["0 | 101", "0 wys positief; 101₂ = 5.", "Dus: +5."] }, { title: "Voorbeeld B: −5", rows: ["1 | 101", "1 wys negatief; omvang bly 101₂ = 5.", "Dus: −5."] }] },
  { title: "2. Twee-komplement voorstelling", examples: [{ title: "Voorbeeld A: −3", rows: ["+3 = 0011", "Inverseer: 1100", "Tel 1 by: 1101 = −3."] }, { title: "Voorbeeld B: −6", rows: ["+6 = 0110", "Inverseer: 1001", "Tel 1 by: 1010 = −6."] }] },
  { title: "Uitbreiding van buslengte", examples: [{ title: "Voorbeeld A: unsigned", rows: ["1011₂ na 8 bis", "Voeg nulle links by.", "0000 1011₂."] }, { title: "Voorbeeld B: getekend", rows: ["1011₂ na 8 bis", "Tekenbis is 1; herhaal dit links.", "1111 1011₂."] }] },
  { title: "Oorloopreël", examples: [{ title: "Voorbeeld A: positiewe oorloop", rows: ["0111 (+7) + 0001 (+1)", "= 1000 (negatiewe tekenpatroon)", "Twee + insette, − resultaat: oorloop."] }, { title: "Voorbeeld B: negatiewe oorloop", rows: ["1000 (−8) + 1111 (−1)", "= 0111 (positiewe tekenpatroon)", "Twee − insette, + resultaat: oorloop."] }] },
  { title: "Maal v. positiewe getalle", examples: [{ title: "Voorbeeld A: 5 × 3", rows: ["C=0, A=0000, Q=0011, M=0101.", "Toets Q₀; tel M by A indien Q₀=1; skuif C-A-Q.", "Finale A|Q = 0000 1111 = 15."] }, { title: "Voorbeeld B: 4 × 6", rows: ["C=0, A=0000, Q=0110, M=0100.", "Werk vier toets/tel/skuif-rye.", "Finale A|Q = 0001 1000 = 24."] }] },
];
const le3: Array<{ title: string; examples: Example[] }> = [
  { title: "HALWE OPTELLER", examples: [{ title: "Voorbeeld A: 1 + 1", rows: ["A=1, B=1", "S = A XOR B = 0", "C = A AND B = 1 → 10₂."] }, { title: "Voorbeeld B: 1 + 0", rows: ["A=1, B=0", "S = 1 XOR 0 = 1", "C = 1 AND 0 = 0 → 01₂."] }] },
  { title: "VOLOPTELLER", examples: [{ title: "Voorbeeld A: 1 + 1 + Cin 1", rows: ["A=1, B=1, Cin=1", "Som = 1; Cout = 1.", "Dus 1+1+1 = 11₂."] }, { title: "Voorbeeld B: 1 + 0 + Cin 1", rows: ["A=1, B=0, Cin=1", "Som = 0; Cout = 1.", "Dus 1+0+1 = 10₂."] }] },
];
function ExampleBlock({ item }: { item: { title: string; examples: Example[] } }) { const [open, setOpen] = useState(false); return <article className="expansion"><header><span>{item.title}</span><button type="button" onClick={() => setOpen(!open)}><Play className="size-3.5" />{open ? "Versteek voorbeelde" : "Wys 2 voorbeelde"}</button></header>{open ? <div>{item.examples.map(example => <section key={example.title}><b>{example.title}</b><ol>{example.rows.map(row => <li key={row}>{row}</li>)}</ol></section>)}</div> : null}</article>; }
export function Le2ExampleExpansions() { return <section className="example-expansions"><header><span>LE2 / VOORBEELDE PER SUBOPSKRIF</span><h4>Open net die metode wat jy nou hersien.</h4></header>{le2.map(item => <ExampleBlock item={item} key={item.title} />)}</section>; }
export function Le3ExampleExpansions() { const [open,setOpen]=useState(""); const table=(id:string,title:string,heads:string[],rows:string[][])=><article className="expansion expansion--adder"><header><span>{title}</span><button type="button" onClick={()=>setOpen(open===id?"":id)}><Play className="size-3.5"/>{open===id?"Versteek voorbeelde":"Wys 2 voorbeelde"}</button></header>{open?<div className="adder-examples"><table><thead><tr>{heads.map(head=><th key={head}>{head}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table><p><b>Lees die gemerkte rye:</b> elke ry toon een volledige voorbeeld met insette, Som en oordrag.</p></div>:null}</article>; return <section className="example-expansions example-expansions--logic"><header><span>LE3 / OPTELLERVOORBEELDE</span><h4>Vergelyk die insette, Som en oordrag in waarheidstabelvorm.</h4></header>{table("half","HALWE OPTELLER",["Voorbeeld","A","B","S","C"],[["A","1","1","0","1"],["B","1","0","1","0"]])}{table("full","VOLOPTELLER",["Voorbeeld","A","B","Cin","Som","Cout"],[["A","1","1","1","1","1"],["B","1","0","1","0","1"]])}</section>; }
