/* Ingenieurswerkboek: volledige, selfnasienbare Vraag 1–4-werkvelle. */
import { Button } from "@/components/ui/button";
import { Check, RotateCcw } from "lucide-react";
import { useState } from "react";
import "./practice-additions.css";

type Cell = { given?: string; answer?: string };
type Conversion = { id: string; binary: Cell; decimal: Cell; hex: Cell; note: string };
type Short = { prompt: string; answer: string; note: string };
type Ias = { word: string; pc: string; result: string; rows: [string, string, string, string][] };
type Variant = { conversions: Conversion[]; q2: Short[]; q3: Short[]; ias: Ias };

const variants: Record<string, Variant> = {
  "ha1-1": { conversions:[{id:"a",binary:{},decimal:{given:"44"},hex:{answer:"2C"},note:"44₁₀=2C₁₆."},{id:"b",binary:{answer:"10011101"},decimal:{given:"157"},hex:{},note:"157=128+16+8+4+1."},{id:"c",binary:{given:"01100000"},decimal:{answer:"96"},hex:{},note:"64+32."},{id:"d",binary:{given:"101010.111"},decimal:{answer:"42.875"},hex:{},note:".111₂=.875."}],q2:[{prompt:"−6 as 4-bis twee-komplement",answer:"1010",note:"0110→1001→1010."},{prompt:"0111 + 0001: signed overflow?",answer:"ja",note:"Twee positiewe gee 1000."},{prompt:"Finale A|Q vir 0101 × 0011",answer:"00001111",note:"Produk = 15."}],q3:[{prompt:"Halwe opteller: S vir A=1,B=1",answer:"0",note:"S=A XOR B."},{prompt:"Halwe opteller: C vir A=1,B=1",answer:"1",note:"C=A AND B."},{prompt:"Hek wat 1 gee wanneer insette verskil",answer:"XOR",note:"XOR / XOF."}],ias:{word:"M(1): SUB M(8) | STORE M(9); M(8)=5; AC begin by 14.",pc:"1",result:"AC=9",rows:[["Gaan haal links","MAR","1","PC se volgende adres."],["","MBR","SUB M(8), STORE M(9)","Lees die 40-bis woord."],["","IBR","STORE M(9)","Regter instruksie wag."],["","IR","SUB M(8)","Linker instruksie."],["Uitvoer links","MBR","5","Lees M(8)."],["","AC","9","14−5."],["Gaan haal regs","IR","STORE M(9)","Haal uit IBR."],["Uitvoer regs","MBR","9","Skryf AC na M(9)."]]}},
  "ha1-2": { conversions:[{id:"a",binary:{answer:"00111010"},decimal:{given:"58"},hex:{},note:"32+16+8+2."},{id:"b",binary:{given:"10101101"},decimal:{answer:"173"},hex:{},note:"128+32+8+4+1."},{id:"c",binary:{given:"11010110"},decimal:{answer:"214"},hex:{},note:"128+64+16+4+2."},{id:"d",binary:{given:"11010"},decimal:{answer:"26"},hex:{},note:"16+8+2."}],q2:[{prompt:"−3 as 4-bis twee-komplement",answer:"1101",note:"0011→1100→1101."},{prompt:"Teken-en-omvang se grootste positiewe 4-bis waarde",answer:"7",note:"Drie omvangsbisse gee 7."},{prompt:"Finale A|Q vir 0100 × 0110",answer:"00011000",note:"4×6=24."}],q3:[{prompt:"Volopteller: aantal insette",answer:"3",note:"A,B,Cin."},{prompt:"Volopteller se Som vir 1+1+1",answer:"1",note:"1+1+1=11₂."},{prompt:"Wat behou ’n houwipkring?",answer:"toestand",note:"Terugvoer hou Q."}],ias:{word:"M(1): LOAD M(12) | ADD M(13); M(12)=9; M(13)=4.",pc:"1",result:"AC=13",rows:[["Gaan haal links","MAR","1","PC→MAR."],["","MBR","LOAD M(12), ADD M(13)","Lees woord."],["","IBR","ADD M(13)","Bewaar regs."],["","IR","LOAD M(12)","Linker instruksie."],["Uitvoer links","AC","9","Laai M(12)."],["Gaan haal regs","IR","ADD M(13)","Gebruik IBR."],["Uitvoer regs","MBR","4","Lees M(13)."],["","AC","13","9+4."]]}},
  "ha1-3": { conversions:[{id:"a",binary:{given:"00111111"},decimal:{answer:"63"},hex:{},note:"32+16+8+4+2+1."},{id:"b",binary:{answer:"11010110"},decimal:{given:"214"},hex:{},note:"128+64+16+4+2."},{id:"c",binary:{},decimal:{answer:"2989"},hex:{given:"BAD"},note:"11×256+10×16+13."},{id:"d",binary:{answer:"1110.1001"},decimal:{given:"14.5625"},hex:{},note:"0.5625 gee .1001₂."}],q2:[{prompt:"Unsigned uitbreiding van 1011 na 8 bis",answer:"00001011",note:"Voeg nulle links by."},{prompt:"Twee-komplement uitbreiding van 1011 na 8 bis",answer:"11111011",note:"Herhaal tekenbis."},{prompt:"0110 × 0011 in desimaal",answer:"18",note:"6×3."}],q3:[{prompt:"AND: 1 EN 0",answer:"0",note:"Albei moet 1 wees."},{prompt:"NOT: NIE 0",answer:"1",note:"NOT keer om."},{prompt:"Volopteller se dra-uitset",answer:"Cout",note:"Carry out."}],ias:{word:"M(1): LOAD M(20) | SUB M(21); M(20)=17; M(21)=8.",pc:"1",result:"AC=9",rows:[["Gaan haal links","MAR","1","PC→MAR."],["","MBR","LOAD M(20), SUB M(21)","Lees woord."],["","IBR","SUB M(21)","Wag regs."],["","IR","LOAD M(20)","Voer links."],["Uitvoer links","AC","17","Laai operand."],["Gaan haal regs","MAR","21","Adres uit IBR."],["Uitvoer regs","MBR","8","Lees M(21)."],["","AC","9","17−8."]]}},
  "proef-a": { conversions:[{id:"a",binary:{answer:"01011101"},decimal:{given:"93"},hex:{answer:"5D"},note:"93=64+16+8+4+1."},{id:"b",binary:{answer:"11101010"},decimal:{answer:"234"},hex:{given:"EA"},note:"E=1110,A=1010."},{id:"c",binary:{answer:"10011.011"},decimal:{given:"19.375"},hex:{},note:".375=.011₂."},{id:"d",binary:{given:"01111110"},decimal:{answer:"126"},hex:{},note:"64+32+16+8+4+2."}],q2:[{prompt:"4-bis twee-komplement: −8",answer:"1000",note:"Laagste waarde."},{prompt:"Oorloop by 1000 + 1111?",answer:"ja",note:"Twee negatiewe gee positief."},{prompt:"5×5 as 8-bis binêr",answer:"00011001",note:"25₁₀."}],q3:[{prompt:"OF: 0 OF 1",answer:"1",note:"Ten minste een 1."},{prompt:"XOR: 1 XOF 1",answer:"0",note:"Dieselfde insette."},{prompt:"Wat is Cin?",answer:"dra inset",note:"Carry-in."}],ias:{word:"M(1): LOAD M(30) | ADD M(31); M(30)=8; M(31)=6.",pc:"1",result:"AC=14",rows:[["Gaan haal links","MAR","1","PC kies woord."],["","MBR","LOAD M(30), ADD M(31)","Lees woord."],["","IBR","ADD M(31)","Bewaar regs."],["","IR","LOAD M(30)","Linker opcode."],["Uitvoer links","AC","8","Laai M(30)."],["Gaan haal regs","IR","ADD M(31)","Uit IBR."],["Uitvoer regs","MBR","6","Lees M(31)."],["","AC","14","8+6."]]}},
  "proef-b": { conversions:[{id:"a",binary:{answer:"10101111"},decimal:{given:"175"},hex:{answer:"AF"},note:"175=128+32+8+4+2+1."},{id:"b",binary:{answer:"11000011"},decimal:{answer:"195"},hex:{given:"C3"},note:"C=1100,3=0011."},{id:"c",binary:{answer:"101101.101"},decimal:{given:"45.625"},hex:{},note:".625=.101₂."},{id:"d",binary:{given:"10001111"},decimal:{answer:"143"},hex:{},note:"128+8+4+2+1."}],q2:[{prompt:"Teken-en-omvang: 1 101 beteken",answer:"-5",note:"Teken 1; omvang 5."},{prompt:"0111 + 0010: signed overflow?",answer:"ja",note:"+7+2 kan nie pas nie."},{prompt:"4×7 as binêre produk",answer:"00011100",note:"28₁₀."}],q3:[{prompt:"Som-bis van ’n halwe opteller",answer:"XOR",note:"S=A XOR B."},{prompt:"Cout vir 1+0+1",answer:"1",note:"Totaal 10₂."},{prompt:"Wipkring se uitset behou ’n",answer:"toestand",note:"Sequentiële logika."}],ias:{word:"M(1): LOAD M(40) | SUB M(41); M(40)=15; M(41)=9.",pc:"1",result:"AC=6",rows:[["Gaan haal links","MAR","1","PC se adres."],["","MBR","LOAD M(40), SUB M(41)","Hele woord."],["","IBR","SUB M(41)","Regter instruksie."],["","IR","LOAD M(40)","Linker instruksie."],["Uitvoer links","AC","15","Laai M(40)."],["Gaan haal regs","MAR","41","Adres uit IBR."],["Uitvoer regs","MBR","9","Lees M(41)."],["","AC","6","15−9."]]}},
};
function norm(x:string){return x.toUpperCase().replaceAll(" ","").replaceAll(",",".").trim()}
function AnswerField({id,expected,value,marked,onChange}:{id:string;expected:string;value:string;marked:boolean;onChange:(v:string)=>void}){const ok=norm(value)===norm(expected);return <><input aria-label={id} className={`answer-input ${marked?(ok?"answer-input--correct":"answer-input--wrong"):""}`} value={value} onChange={e=>onChange(e.target.value)}/>{marked&&!ok?<small className="practice-note">{expected}</small>:null}</>}
export function ConversionQuestion({paperId}:{paperId:string}){const d=variants[paperId];const [v,setV]=useState<Record<string,string>>({});const [m,setM]=useState(false);const expected=Object.fromEntries(d.conversions.flatMap(r=>(["binary","decimal","hex"] as const).filter(k=>r[k].answer).map(k=>[`${r.id}-${k}`,r[k].answer!]))) as Record<string,string>;const score=Object.keys(expected).filter(k=>norm(v[k]??"")===norm(expected[k])).length;return <section className="paper-question conversion-question"><div className="paper-question__title"><b>VRAAG 1</b><span>LE1 / GETALLESTELSELS</span><em>5p</em></div><p>Voltooi die antwoordblad: plaas elke gegewe waarde en antwoord in die toepaslike <b>Binêr</b>-, <b>Desimaal</b>- of <b>Heksadesimaal</b>-kolom.</p><div className="overflow-x-auto"><table className="conversion-worksheet"><thead><tr><th>Item</th><th>Binêr</th><th>Desimaal</th><th>Heksadesimaal</th></tr></thead><tbody>{d.conversions.map(r=><tr key={r.id}><th>({r.id})</th>{(["binary","decimal","hex"] as const).map(k=>{const c=r[k];const id=`${r.id}-${k}`;return <td key={k}>{c.given??(c.answer?<AnswerField id={id} expected={c.answer} value={v[id]??""} marked={m} onChange={x=>{setV({...v,[id]:x});setM(false)}}/>:"—")}</td>})}</tr>)}</tbody></table></div><footer className="short-question__footer"><Button className="mark-button" onClick={()=>setM(true)}><Check className="size-4"/>Merk Vraag 1</Button>{m?<b>{score}/{Object.keys(expected).length} korrek</b>:null}</footer></section>}
export function ShortQuestion({paperId,kind}:{paperId:string;kind:"q2"|"q3"}){const d=variants[paperId][kind];const [v,setV]=useState<Record<number,string>>({});const [m,setM]=useState(false);const title=kind==="q2"?["VRAAG 2","LE2 / HEELGETALVOORSTELLING EN BEREKENING","21p"]:["VRAAG 3","LE3 / DIGITALE LOGIKA","9p"];const score=d.filter((x,i)=>norm(v[i]??"")===norm(x.answer)).length;return <section className="paper-question short-question"><div className="paper-question__title"><b>{title[0]}</b><span>{title[1]}</span><em>{title[2]}</em></div><p>Werk kort, maar wys die kernpatroon of term. Merk daarna om jou antwoord en hersieningsnota te sien.</p><div className="short-question__rows">{d.map((x,i)=>{const ok=norm(v[i]??"")===norm(x.answer);return <label key={x.prompt} className={m&&!ok?"short-question__wrong":""}><b>{String.fromCharCode(97+i)}.</b><span>{x.prompt}</span><input value={v[i]??""} onChange={e=>{setV({...v,[i]:e.target.value});setM(false)}} placeholder="Jou antwoord"/>{m?<em className={ok?"short-question__good":""}>{ok?"Korrek":`${x.answer} — ${x.note}`}</em>:null}</label>})}</div><footer className="short-question__footer"><Button className="mark-button" onClick={()=>setM(true)}><Check className="size-4"/>Merk {title[0]}</Button><button type="button" onClick={()=>{setV({});setM(false)}}><RotateCcw className="size-4"/>Herstel</button>{m?<b>{score}/{d.length} korrek</b>:null}</footer></section>}
export function IasCodeWorksheet({paperId}:{paperId:string}){const d=variants[paperId].ias;const [v,setV]=useState<Record<number,string>>({});const [m,setM]=useState(false);const score=d.rows.filter((x,i)=>norm(v[i]??"")===norm(x[2])).length;return <section className="ias-code-worksheet"><header><span>IAS-SCENARIO / TKA-ANTWOORDBLAD</span><h4>Voltooi die registerwaardes vir die gegewe kode.</h4><p><code>{d.word}</code> PC = {d.pc}. Volg die fases: gaan haal links, voer links uit, gaan haal regs en voer regs uit.</p></header><div className="overflow-x-auto"><table><thead><tr><th>Fase</th><th>Register</th><th>Jou waarde</th><th>Waarom?</th></tr></thead><tbody>{d.rows.map((x,i)=>{const ok=norm(v[i]??"")===norm(x[2]);return <tr key={`${x[0]}-${i}`}><td>{x[0]}</td><td>{x[1]}</td><td><AnswerField id={`ias-${paperId}-${i}`} expected={x[2]} value={v[i]??""} marked={m} onChange={z=>{setV({...v,[i]:z});setM(false)}}/></td><td>{m?<span className={ok?"ias-code-worksheet__good":"ias-code-worksheet__bad"}>{x[3]}</span>:""}</td></tr>})}</tbody></table></div><footer><Button className="mark-button" onClick={()=>setM(true)}><Check className="size-4"/>Merk IAS-stappe</Button>{m?<b>{score}/{d.rows.length} korrek · {d.result}</b>:null}</footer></section>}
